### PR TITLE
non-flash version with link on the right

### PR DESCRIPTION
**Pull request by flashbackzoo**
Split view expanded
share-draft-v2-a

Edit view collapsed
share-draft-v2-b

### CODE REVIEW

**Comment by A7DC** [comment]
Content:

"Copy and send this draft link to anyone. *'Ctrl + c' (Win), 'Cmd + c' (OSX)."

**Comment by A7DC** [comment]
Functionality to include:

* URL is automatically highlighted on click of the 'share draft' button.
In the event that the user no longer has the URL highlighted:
* Clicking the input highlights entire URL

**Comment by A7DC** [comment]
@flashbackzoo If you can make it so the copying shortcuts only appear for their relative operating systems, that would be great if not too much effort?

**Comment by flashbackzoo** [comment]
share-link

**Pull request merged**
