### PR TITLE
Fix preview icons for 3.3

### PR DESCRIPTION
**Pull request by scott1702**
Fix for the preview icons not showing (https://github.com/silverstripe-labs/silverstripe-sharedraftcontent/issues/52)

This fix for 3.3 will break the icons for 3.2/3.1 in the same way, so a new branch may need to be made before this is merged.

### CODE REVIEW

**Comment by tractorcow** [comment]
can you please update composer.json to require ~3.3? Otherwise users will be able to install a non-compatible version with 3.2.

If you do this, I'll update the branches and set the prior dependency to `~3.1 <3.3`

**Comment by scott1702** [comment]
Updated :)

**Comment by tractorcow** [comment]
Tests for 5.6 aren't working... something is wrong with travis.yml (although I can't spot it immediately).

**Comment by tractorcow** [comment]
Ah no wonder. :D

**Comment by scott1702** [comment]
Closed with https://github.com/silverstripe-labs/silverstripe-sharedraftcontent/pull/55

**Pull request closed without merging**
