### PR TITLE
Create de.yml

### PR DESCRIPTION
**Pull request by moritz-sauer-13**
Added german translations.

### CODE REVIEW

**Comment by moritz-sauer-13** [comment]
Added german translations.

**Comment by GuySartorelli** [comment]
Thanks for doing this.
We use transifex.com for translations. Please submit your translations on transifex following [the contribution guidelines](https://docs.silverstripe.org/en/5/contributing/translations/).

**Comment by moritz-sauer-13** [comment]
Thanks for the tip! I have just done it in Transifex. How long do you think it will take for this to be merged?

**Comment by GuySartorelli** [comment]
We typically merge those in each February, May, August, and November

**Pull request closed without merging**
