### PR TITLE
FIX Rename file to match class name

### PR DESCRIPTION
**Pull request by emteknetnz**
Fix for https://github.com/silverstripe/silverstripe-sharedraftcontent/issues/127

### CODE REVIEW

**Comment by obj63mc** [comment]
Just checking if this can be merged?

**Review by dhensby — APPROVED** [review]

**Comment by emteknetnz** [comment]
There was a broken behat test, possibly related to the use of old travis shared config.  I tried rerunning the individual build though it still uses the old config.  I've just retriggered a build that will use an updated shared config by git undoing the last commit and re-commiting.  It creates a new hash though the code is the same as what was approved.

**Comment by emteknetnz** [comment]
Behat test passed on rerun

**Comment by emteknetnz** [comment]
@obj63mc I've tagged 2.3.6 and 2.4.2 for you which both contain this fix

**Pull request merged**
