### PR TITLE
Updating travis provisioner

### PR DESCRIPTION
**Pull request by dhensby**
Travis will now be more resilient to `composer self-update` failures

### CODE REVIEW

**Comment by dhensby** [comment]
bump

**Comment by assertchris** [comment]
Tests are failing, yo!

**Comment by dhensby** [comment]
Unrelated @assertchris

**Comment by dhensby** [comment]
ping @assertchris :)

**Comment by assertchris** [comment]
Please rebase - I've fixed the tests.

**Comment by dhensby** [comment]
ping @assertchris

**Pull request merged**
